os: linux
language: go

go: 1.13.x

env:
  global:
    - GO111MODULE=on

addons:
  apt:
    packages:
      - snapcraft

after_success:
  - test -n "$TRAVIS_TAG" && openssl aes-256-cbc -K $encrypted_634cf8e7b6b8_key -iv $encrypted_634cf8e7b6b8_iv -in snap.login.enc -out snap.login -d
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
