site_name: manala
repo_url: https://github.com/manala/manala/

markdown_extensions:
  - admonition

theme:
  name: readthedocs
  hljs_languages:
    - yaml

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Overview: overview.md
  - Usage: usage.md
  - Contributing: contributing.md
