name: Documentation

on:
  push:
    branches:
      - master

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        # See: https://github.com/mhausenblas/mkdocs-deploy-gh-pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
